name: foodies
version: 1.0.0
description: Application to View Food and Its Category.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: 5.0.3
  flutter_bloc: 8.1.2
  lottie: 1.2.2
  equatable: 2.0.5
  dartz: 0.10.1
  get_it: 7.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  bloc_test: 9.1.1
  mocktail: 0.3.0
  flutter_test:
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

